name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache folders
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-bin
        path: |
          ~/bin
          ~/.local/lib

    - name: Create bin folder
      run: |
        mkdir -vp "$HOME/bin"
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Install Luna
      run: |
        command -v luna && exit
        git clone "https://github.com/ndless-nspire/Luna" ~/Luna
        cd ~/Luna
        make
        install -Dm755 luna ~/bin/luna
    
    - name: Install nspire-merge
      run: |
        command -v nspire-merge && exit
        git clone "https://github.com/alexcoder04/nspire-merge" ~/nspire-merge
        cd ~/nspire-merge
        install -Dm755 nspire-merge ~/bin/nspire-merge
        pip install Pillow

    - name: Build project
      run: make clean build

    - name: Save tns
      uses: actions/upload-artifact@v3
      with:
        name: tns
        path: |
          n-2048.tns
